/** biome-ignore-all lint/style/useNamingConvention: matching spec names */
/** biome-ignore-all lint/style/noNamespace: organisation purposes */

/**
 * Relevant parts of the OpenAPI JSON Specification v3.0.0x in (imperfect) TypeScript form.
 *
 * Limitations include:
 * - Regular expressions are widened to strings.
 * - No OpenID or OAuth security schemes (and bearer is less strongly typed).
 * - Some union and mutual exlusion types are omitted.
 *
 * Therefore it's worth noting that an object conforming to this export interface is **not
 * guaranteed** to conform to the JSON spec, this is really only here for convenience.
 *
 * And no this was not generated by AI... but maybe it should've been...
 *
 * @see {@link https://spec.openapis.org/oas/3.0/schema/2024-10-18}
 */
export namespace OAS {
    export interface RootDocument {
        $schema?: string;

        openapi: `3.0.${number}`;

        info: Info;

        externalDocs?: ExternalDocumentation;

        servers?: Server[];

        tags?: Tag[];

        paths: Paths;

        components?: Components;
    }

    export interface Reference {
        $ref: string;
    }

    export interface Info {
        title: string;

        description?: string;

        termsOfService?: string;

        contact?: Contact;

        license?: License;

        version: string;
    }

    export interface Contact {
        name?: string;

        url?: string;

        email?: string;
    }

    export interface License {
        name: string;

        url?: string;
    }

    export interface Server {
        url: string;

        description?: string;

        variables: ServerVariable;
    }

    export interface ServerVariable {
        enum: string[];

        default: string;

        description?: string;
    }

    export interface Components {
        schemas?: Record<string, Reference | Schema>;

        responses?: Record<string, Reference | Response>;

        parameters?: Record<string, Reference | Parameter>;

        requestBodies?: Record<string, Reference | RequestBody>;

        securitySchemes?: Record<string, Reference | SecurityScheme>;
    }

    export interface Schema {
        title?: string;

        multipleOf?: number;

        maximum?: number;

        exclusiveMaximum?: number;

        minimum?: number;

        exclusiveMinimum?: number;

        maxLength?: number;

        minLength?: number;

        pattern?: string;

        maxItems?: number;

        minItems?: number;

        uniqueItems?: boolean;

        maxProperties?: number;

        minProperties?: number;

        required?: string[];

        enum?: unknown[];

        type?: "array" | "boolean" | "integer" | "number" | "object" | "string";

        not?: Schema | Reference;

        allOf?: (Schema | Reference)[];

        oneOf?: (Schema | Reference)[];

        anyOf?: (Schema | Reference)[];

        items?: Schema | Reference;

        properties?: Record<string, Schema | Reference>;

        additionalProperties?: Schema | Reference | boolean;

        description?: string;

        format?: string;

        default?: unknown;

        nullable?: boolean;

        discriminator?: Discriminator;

        readOnly?: boolean;

        writeOnly?: boolean;

        example?: unknown;

        externalDocs?: ExternalDocumentation;

        deprecated?: boolean;

        xml?: XML;
    }

    export interface Discriminator {
        propertyName: string;

        mapping?: { type: string; [key: string]: unknown };
    }

    export interface XML {
        name?: string;

        namespace?: string;

        prefix?: string;

        attribute?: boolean;

        wrapped?: boolean;
    }

    export interface Response {
        description: string;

        headers?: Header | Reference;

        content?: MediaTypeMap;

        links?: Link | Reference;
    }

    type MediaTypeMap = { [k in "application/json" | "text/html"]?: MediaType };

    export interface MediaType {
        schema?: Schema | Reference;

        example?: unknown;

        examples?: Example | Reference;
    }

    export interface Example {
        summary?: string;

        description?: string;

        value?: unknown;

        externalValue?: string;
    }

    export interface Header {
        description?: string;

        required?: boolean;

        deprecated?: boolean;

        allowEmptyValue?: boolean;

        style?: "simple";

        explode?: boolean;

        allowReserved?: boolean;

        schema?: Schema | Reference;

        content?: MediaTypeMap;

        example?: unknown;

        examples?: Example | Reference;
    }

    export interface Paths {
        [key: string]: PathItem;
    }

    export interface PathItem {
        $ref?: string;

        summary?: string;

        description?: string;

        get?: Operation;

        put?: Operation;

        post?: Operation;

        delete?: Operation;

        options?: Operation;

        head?: Operation;

        patch?: Operation;

        trace?: Operation;

        servers?: Server[];

        parameters?: (Parameter | Reference)[];
    }

    export interface Operation {
        tags?: string[];

        summary?: string;

        description?: string;

        externalDocs?: ExternalDocumentation;

        operationId?: string;

        parameters?: (Parameter | Reference)[];

        requestBody?: RequestBody | Reference;

        responses: Responses;

        deprecated?: boolean;

        security?: SecurityRequirement[];

        servers?: Server[];
    }

    export interface Responses {
        default?: Response | Reference;

        [key: string]: Response | Reference;
    }

    export interface SecurityRequirement {
        [key: string]: string[];
    }

    export interface Tag {
        name: string;

        description?: string;

        externalDocs?: ExternalDocumentation;
    }

    export interface ExternalDocumentation {
        description?: string;

        url: string;
    }

    interface BaseParameter {
        name: string;

        description?: string;

        required?: boolean;

        deprecated?: boolean;

        allowEmptyValue?: boolean;

        explode?: boolean;

        allowReserved?: boolean;

        schema?: Schema | Reference;

        content?: MediaTypeMap;

        example?: unknown;

        examples?: Example | Reference;
    }

    export interface PathParameter extends BaseParameter {
        in: "path";

        style?: "matrix" | "label" | "simple";

        required: true;
    }

    export interface QueryParameter extends BaseParameter {
        in: "query";

        style?: "form" | "spaceDelimited" | "pipeDelimited" | "deepObject";
    }

    export interface HeaderParameter extends BaseParameter {
        in: "header";

        style?: "simple";
    }

    export interface CookieParameter extends BaseParameter {
        in: "cookie";

        style?: "form";
    }

    type Parameter = PathParameter | QueryParameter | HeaderParameter | CookieParameter;

    export interface RequestBody {
        description?: string;

        content: MediaTypeMap;

        required?: boolean;
    }

    export interface APIKeySecurityScheme {
        type: "apiKey";

        name: string;

        in: "header" | "query" | "cookie";

        description?: string;
    }

    export interface HTTPSecurityScheme {
        scheme: string;

        bearerFormat?: string;

        description?: string;

        type: "http";
    }

    type SecurityScheme = APIKeySecurityScheme | HTTPSecurityScheme;

    export interface Link {
        operationId?: string;

        operationRef?: string;

        parameters?: unknown;

        requestBody?: unknown;

        description?: string;

        server?: Server;
    }
}
